default: &default
development:
  adapter: mysql2rgeo
  host: 127.0.0.1
  database: ChatYogi
  encoding: utf8
  username: root
  password: j2ee

test: &test
  adapter: mysql2rgeo
  database: ChatYogi
  encoding: utf8
  username: root
  password: j2ee

production: &production
  adapter: mysql2rgeo
  database: ChatYogi
  encoding: utf8
  username: root
  password: j2ee
  pool: 5
  socket: /tmp/mysql.sock
