default: &default
development:
  adapter: mysql2
  host: 127.0.0.1
  database: ChatYogi
  encoding: utf8
  username: root
  password: j2ee
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql2
  database: ChatYogi
  encoding: utf8
  username: root
  password: j2ee
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

production: &production
  adapter: mysql2
  database: ChatYogi
  encoding: utf8
  username: root
  password: j2ee
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
